steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - './apps/frontend'
      - '-t'
      - 'us-central1-docker.pkg.dev/next-go-445113/next-go-frontend:latest'
      - '-f'
      - 'apps/frontend/Dockerfile'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/next-go-445113/next-go-frontend:latest'
#  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#    args:
#      - 'run'
#      - 'deploy'
#      - '${_SERVICE}'
#      - '--image=${_IMAGE}:$BUILD_ID'
#      - '--region=${_REGION}'
#      - '--allow-unauthenticated'
options:
  logging: CLOUD_LOGGING_ONLY