steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - './apps/frontend'
      - '-t'
      - '${_IMAGE}:latest'
      - '-f'
      - 'apps/frontend/Dockerfile'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_IMAGE}:latest'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE}'
      - '--image'
      - '${_IMAGE}:latest'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
options:
  logging: CLOUD_LOGGING_ONLY