steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - './apps/job'
      - '-t'
      - '${_IMAGE}:latest'
      - '-f'
      - 'apps/job/Dockerfile'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_IMAGE}:latest'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'jobs'
      - 'deploy'
      - '${_CLOUD_RUN_SERVICE}'
      - '--image'
      - '${_IMAGE}:latest'
      - '--region'
      - '${_REGION}'
options:
  logging: CLOUD_LOGGING_ONLY