steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - './apps/backend'
      - '-t'
      - '${_IMAGE}:latest'
      - '-f'
      - 'apps/backend/Dockerfile'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_IMAGE}:latest'
options:
  logging: CLOUD_LOGGING_ONLY