networks:
  next_go:
    driver: bridge

services:
  frontend:
    networks:
      - next_go
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./apps/frontend
          target: ./app/apps/frontend
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
    volumes:
      - ./apps/frontend:/app
    depends_on:
      - backend

  grpc_frontend:
    networks:
      - next_go
    build:
      context: ./apps/grpc_frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3001:3000
    develop:
      watch:
        - action: sync
          path: ./apps/grpc_frontend
          target: ./app/apps/grpc_frontend
    restart: always
    environment:
      - NEXT_PUBLIC_BACKEND_URL=host.docker.internal:50051
    volumes:
      - ./apps/grpc_frontend:/app
    depends_on:
      - backend
      - grpc_backend

  envoy:
    build:
      context: ./infra/envoy
      dockerfile: Dockerfile.dev
    container_name: envoy-grpc-proxy
    ports:
      - "9000:9000"

  backend:
    networks:
      - next_go
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    develop:
      watch:
        - action: sync
          path: ./apps/backend
          target: ./app/apps/backend
    volumes:
      - ./apps/backend:/app
    env_file:
      - .env.local
    depends_on:
      - db

  grpc_backend:
    networks:
      - next_go
    build:
      context: ./apps/grpc_backend
      dockerfile: Dockerfile.dev
    ports:
      - 8082:8080
    develop:
      watch:
        - action: sync
          path: ./apps/grpc_backend
          target: ./app/apps/grpc_backend
    volumes:
      - ./apps/grpc_backend:/app
    env_file:
      - .env.local
    depends_on:
      - db

  job:
    networks:
      - next_go
    build:
      context: ./apps/job
      dockerfile: Dockerfile.dev
    ports:
      - 8081:8080
    volumes:
      - ./apps/job:/app
    command: ["go", "run", "./src/main.go"]
    env_file:
      - .env.local
    environment:
      NEXT_PUBLIC_API_URL: "http://backend:8080"

  db:
    image: "postgres:16-alpine"
    networks:
      - next_go
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - db-store:/var/lib/postgresql/data

  test_db:
    image: "postgres:16-alpine"
    networks:
      - next_go
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=test_postgres
    volumes:
      - test-db-store:/var/lib/postgresql/data

volumes:
  db-store:
    name: db-store
  test-db-store:
    name: test-db-store
  grpc_backend:
    name: grpc_backend