// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type System struct {
	ID         pgtype.UUID
	SystemName string
	CreatedAt  pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	SystemID  pgtype.UUID
	Name      string
	Email     string
	CreatedAt pgtype.Timestamp
}
