// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user_insert.sql

package sqlc

import (
	"context"
)

const insertUser = `-- name: InsertUser :one
INSERT INTO "user" (name, email) VALUES ($1, $2) RETURNING id, name, email, created_at
`

type InsertUserParams struct {
	Name  string
	Email string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.Name, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
