FROM golang:1.22-alpine

WORKDIR /app

COPY ./scripts /scripts

RUN go install github.com/air-verse/air@latest
// 必要な時にバージョン指定
RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.toml"]
