ARG GO_VERSION=1.22.4
FROM golang:1.22.4-alpine AS builder

# 作業ディレクトリの設定
WORKDIR /app
RUN apk add --no-cache git
COPY . .

# モジュールのダウンロード
RUN go mod download

RUN go build -o main .

EXPOSE 8080
RUN chmod +x main
CMD ["ls", "-l", "./main"]
CMD ["./main"]
