// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewSystem struct {
	SystemName string `json:"systemName"`
}

type Query struct {
}

type System struct {
	ID         string `json:"id"`
	SystemName string `json:"system_name"`
}
