// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file order.proto (package grpc_backend.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file order.proto.
 */
export const file_order: GenFile = /*@__PURE__*/
  fileDesc("CgtvcmRlci5wcm90bxIPZ3JwY19iYWNrZW5kLnYxInYKBU9yZGVyEg8KB3VzZXJfaWQYASABKAMSEAoIb3JkZXJfaWQYAiABKAMSEAoIdXNlcm5hbWUYAyABKAkSEgoKcHJvZHVjdF9pZBgEIAEoAxIQCghxdWFudGl0eRgFIAEoAxISCgpvcmRlcl9kYXRlGAYgASgJIiQKEUxpc3RPcmRlcnNSZXF1ZXN0Eg8KB3VzZXJfaWQYASABKAMiOwoSTGlzdE9yZGVyc1Jlc3BvbnNlEiUKBU9yZGVyGAEgASgLMhYuZ3JwY19iYWNrZW5kLnYxLk9yZGVyIksKEkNyZWF0ZU9yZGVyUmVxdWVzdBIPCgd1c2VyX2lkGAEgASgDEhIKCnByb2R1Y3RfaWQYAiABKAMSEAoIcXVhbnRpdHkYAyABKAMiPAoTQ3JlYXRlT3JkZXJSZXNwb25zZRIlCgVPcmRlchgBIAEoCzIWLmdycGNfYmFja2VuZC52MS5PcmRlcjJoCg1PcmRlcnNTZXJ2aWNlElcKCkxpc3RPcmRlcnMSIi5ncnBjX2JhY2tlbmQudjEuTGlzdE9yZGVyc1JlcXVlc3QaIy5ncnBjX2JhY2tlbmQudjEuTGlzdE9yZGVyc1Jlc3BvbnNlMAFCHFoaZ3JwY19iYWNrZW5kL3NyYy9nZW4vcHJvdG9iBnByb3RvMw");

/**
 * @generated from message grpc_backend.v1.Order
 */
export type Order = Message<"grpc_backend.v1.Order"> & {
  /**
   * @generated from field: int64 user_id = 1;
   */
  userId: bigint;

  /**
   * @generated from field: int64 order_id = 2;
   */
  orderId: bigint;

  /**
   * @generated from field: string username = 3;
   */
  username: string;

  /**
   * @generated from field: int64 product_id = 4;
   */
  productId: bigint;

  /**
   * @generated from field: int64 quantity = 5;
   */
  quantity: bigint;

  /**
   * @generated from field: string order_date = 6;
   */
  orderDate: string;
};

/**
 * Describes the message grpc_backend.v1.Order.
 * Use `create(OrderSchema)` to create a new message.
 */
export const OrderSchema: GenMessage<Order> = /*@__PURE__*/
  messageDesc(file_order, 0);

/**
 * @generated from message grpc_backend.v1.ListOrdersRequest
 */
export type ListOrdersRequest = Message<"grpc_backend.v1.ListOrdersRequest"> & {
  /**
   * @generated from field: int64 user_id = 1;
   */
  userId: bigint;
};

/**
 * Describes the message grpc_backend.v1.ListOrdersRequest.
 * Use `create(ListOrdersRequestSchema)` to create a new message.
 */
export const ListOrdersRequestSchema: GenMessage<ListOrdersRequest> = /*@__PURE__*/
  messageDesc(file_order, 1);

/**
 * @generated from message grpc_backend.v1.ListOrdersResponse
 */
export type ListOrdersResponse = Message<"grpc_backend.v1.ListOrdersResponse"> & {
  /**
   * @generated from field: grpc_backend.v1.Order Order = 1;
   */
  Order?: Order;
};

/**
 * Describes the message grpc_backend.v1.ListOrdersResponse.
 * Use `create(ListOrdersResponseSchema)` to create a new message.
 */
export const ListOrdersResponseSchema: GenMessage<ListOrdersResponse> = /*@__PURE__*/
  messageDesc(file_order, 2);

/**
 * @generated from message grpc_backend.v1.CreateOrderRequest
 */
export type CreateOrderRequest = Message<"grpc_backend.v1.CreateOrderRequest"> & {
  /**
   * @generated from field: int64 user_id = 1;
   */
  userId: bigint;

  /**
   * @generated from field: int64 product_id = 2;
   */
  productId: bigint;

  /**
   * @generated from field: int64 quantity = 3;
   */
  quantity: bigint;
};

/**
 * Describes the message grpc_backend.v1.CreateOrderRequest.
 * Use `create(CreateOrderRequestSchema)` to create a new message.
 */
export const CreateOrderRequestSchema: GenMessage<CreateOrderRequest> = /*@__PURE__*/
  messageDesc(file_order, 3);

/**
 * @generated from message grpc_backend.v1.CreateOrderResponse
 */
export type CreateOrderResponse = Message<"grpc_backend.v1.CreateOrderResponse"> & {
  /**
   * @generated from field: grpc_backend.v1.Order Order = 1;
   */
  Order?: Order;
};

/**
 * Describes the message grpc_backend.v1.CreateOrderResponse.
 * Use `create(CreateOrderResponseSchema)` to create a new message.
 */
export const CreateOrderResponseSchema: GenMessage<CreateOrderResponse> = /*@__PURE__*/
  messageDesc(file_order, 4);

/**
 * @generated from service grpc_backend.v1.OrdersService
 */
export const OrdersService: GenService<{
  /**
   * @generated from rpc grpc_backend.v1.OrdersService.ListOrders
   */
  listOrders: {
    methodKind: "server_streaming";
    input: typeof ListOrdersRequestSchema;
    output: typeof ListOrdersResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_order, 0);

