// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file user.proto (package grpc_backend.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file user.proto.
 */
export const file_user: GenFile = /*@__PURE__*/
  fileDesc("Cgp1c2VyLnByb3RvEg9ncnBjX2JhY2tlbmQudjEiOAoEVXNlchIPCgd1c2VyX2lkGAEgASgDEhAKCHVzZXJuYW1lGAIgASgJEg0KBWVtYWlsGAMgASgJIhIKEExpc3RVc2Vyc1JlcXVlc3QiOQoRTGlzdFVzZXJzUmVzcG9uc2USJAoFdXNlcnMYASADKAsyFS5ncnBjX2JhY2tlbmQudjEuVXNlcjJiCgxVc2Vyc1NlcnZpY2USUgoJTGlzdFVzZXJzEiEuZ3JwY19iYWNrZW5kLnYxLkxpc3RVc2Vyc1JlcXVlc3QaIi5ncnBjX2JhY2tlbmQudjEuTGlzdFVzZXJzUmVzcG9uc2VCHFoaZ3JwY19iYWNrZW5kL3NyYy9nZW4vcHJvdG9iBnByb3RvMw");

/**
 * @generated from message grpc_backend.v1.User
 */
export type User = Message<"grpc_backend.v1.User"> & {
  /**
   * @generated from field: int64 user_id = 1;
   */
  userId: bigint;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;
};

/**
 * Describes the message grpc_backend.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_user, 0);

/**
 * @generated from message grpc_backend.v1.ListUsersRequest
 */
export type ListUsersRequest = Message<"grpc_backend.v1.ListUsersRequest"> & {
};

/**
 * Describes the message grpc_backend.v1.ListUsersRequest.
 * Use `create(ListUsersRequestSchema)` to create a new message.
 */
export const ListUsersRequestSchema: GenMessage<ListUsersRequest> = /*@__PURE__*/
  messageDesc(file_user, 1);

/**
 * @generated from message grpc_backend.v1.ListUsersResponse
 */
export type ListUsersResponse = Message<"grpc_backend.v1.ListUsersResponse"> & {
  /**
   * @generated from field: repeated grpc_backend.v1.User users = 1;
   */
  users: User[];
};

/**
 * Describes the message grpc_backend.v1.ListUsersResponse.
 * Use `create(ListUsersResponseSchema)` to create a new message.
 */
export const ListUsersResponseSchema: GenMessage<ListUsersResponse> = /*@__PURE__*/
  messageDesc(file_user, 2);

/**
 * @generated from service grpc_backend.v1.UsersService
 */
export const UsersService: GenService<{
  /**
   * @generated from rpc grpc_backend.v1.UsersService.ListUsers
   */
  listUsers: {
    methodKind: "unary";
    input: typeof ListUsersRequestSchema;
    output: typeof ListUsersResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_user, 0);

