// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/order.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	proto "grpc_backend/src/_generated/proto"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// OrdersServiceName is the fully-qualified name of the OrdersService service.
	OrdersServiceName = "grpc_backend.v1.OrdersService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// OrdersServiceListOrdersProcedure is the fully-qualified name of the OrdersService's ListOrders
	// RPC.
	OrdersServiceListOrdersProcedure = "/grpc_backend.v1.OrdersService/ListOrders"
	// OrdersServiceCreateOrderProcedure is the fully-qualified name of the OrdersService's CreateOrder
	// RPC.
	OrdersServiceCreateOrderProcedure = "/grpc_backend.v1.OrdersService/CreateOrder"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	ordersServiceServiceDescriptor           = proto.File_proto_order_proto.Services().ByName("OrdersService")
	ordersServiceListOrdersMethodDescriptor  = ordersServiceServiceDescriptor.Methods().ByName("ListOrders")
	ordersServiceCreateOrderMethodDescriptor = ordersServiceServiceDescriptor.Methods().ByName("CreateOrder")
)

// OrdersServiceClient is a client for the grpc_backend.v1.OrdersService service.
type OrdersServiceClient interface {
	ListOrders(context.Context, *connect.Request[proto.ListOrdersRequest]) (*connect.ServerStreamForClient[proto.ListOrdersResponse], error)
	CreateOrder(context.Context, *connect.Request[proto.CreateOrderRequest]) (*connect.Response[proto.CreateOrderResponse], error)
}

// NewOrdersServiceClient constructs a client for the grpc_backend.v1.OrdersService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOrdersServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OrdersServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &ordersServiceClient{
		listOrders: connect.NewClient[proto.ListOrdersRequest, proto.ListOrdersResponse](
			httpClient,
			baseURL+OrdersServiceListOrdersProcedure,
			connect.WithSchema(ordersServiceListOrdersMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createOrder: connect.NewClient[proto.CreateOrderRequest, proto.CreateOrderResponse](
			httpClient,
			baseURL+OrdersServiceCreateOrderProcedure,
			connect.WithSchema(ordersServiceCreateOrderMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// ordersServiceClient implements OrdersServiceClient.
type ordersServiceClient struct {
	listOrders  *connect.Client[proto.ListOrdersRequest, proto.ListOrdersResponse]
	createOrder *connect.Client[proto.CreateOrderRequest, proto.CreateOrderResponse]
}

// ListOrders calls grpc_backend.v1.OrdersService.ListOrders.
func (c *ordersServiceClient) ListOrders(ctx context.Context, req *connect.Request[proto.ListOrdersRequest]) (*connect.ServerStreamForClient[proto.ListOrdersResponse], error) {
	return c.listOrders.CallServerStream(ctx, req)
}

// CreateOrder calls grpc_backend.v1.OrdersService.CreateOrder.
func (c *ordersServiceClient) CreateOrder(ctx context.Context, req *connect.Request[proto.CreateOrderRequest]) (*connect.Response[proto.CreateOrderResponse], error) {
	return c.createOrder.CallUnary(ctx, req)
}

// OrdersServiceHandler is an implementation of the grpc_backend.v1.OrdersService service.
type OrdersServiceHandler interface {
	ListOrders(context.Context, *connect.Request[proto.ListOrdersRequest], *connect.ServerStream[proto.ListOrdersResponse]) error
	CreateOrder(context.Context, *connect.Request[proto.CreateOrderRequest]) (*connect.Response[proto.CreateOrderResponse], error)
}

// NewOrdersServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOrdersServiceHandler(svc OrdersServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	ordersServiceListOrdersHandler := connect.NewServerStreamHandler(
		OrdersServiceListOrdersProcedure,
		svc.ListOrders,
		connect.WithSchema(ordersServiceListOrdersMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	ordersServiceCreateOrderHandler := connect.NewUnaryHandler(
		OrdersServiceCreateOrderProcedure,
		svc.CreateOrder,
		connect.WithSchema(ordersServiceCreateOrderMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/grpc_backend.v1.OrdersService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OrdersServiceListOrdersProcedure:
			ordersServiceListOrdersHandler.ServeHTTP(w, r)
		case OrdersServiceCreateOrderProcedure:
			ordersServiceCreateOrderHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOrdersServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOrdersServiceHandler struct{}

func (UnimplementedOrdersServiceHandler) ListOrders(context.Context, *connect.Request[proto.ListOrdersRequest], *connect.ServerStream[proto.ListOrdersResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("grpc_backend.v1.OrdersService.ListOrders is not implemented"))
}

func (UnimplementedOrdersServiceHandler) CreateOrder(context.Context, *connect.Request[proto.CreateOrderRequest]) (*connect.Response[proto.CreateOrderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("grpc_backend.v1.OrdersService.CreateOrder is not implemented"))
}
