// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file file.proto (package file, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file file.proto.
 */
export const file_file: GenFile = /*@__PURE__*/
  fileDesc("CgpmaWxlLnByb3RvEgRmaWxlIhIKEExpc3RGaWxlc1JlcXVlc3QiJgoRTGlzdEZpbGVzUmVzcG9uc2USEQoJZmlsZW5hbWVzGAEgAygJMksKC0ZpbGVTZXJ2aWNlEjwKCUxpc3RGaWxlcxIWLmZpbGUuTGlzdEZpbGVzUmVxdWVzdBoXLmZpbGUuTGlzdEZpbGVzUmVzcG9uc2VCBloELi9wYmIGcHJvdG8z");

/**
 * @generated from message file.ListFilesRequest
 */
export type ListFilesRequest = Message<"file.ListFilesRequest"> & {
};

/**
 * Describes the message file.ListFilesRequest.
 * Use `create(ListFilesRequestSchema)` to create a new message.
 */
export const ListFilesRequestSchema: GenMessage<ListFilesRequest> = /*@__PURE__*/
  messageDesc(file_file, 0);

/**
 * @generated from message file.ListFilesResponse
 */
export type ListFilesResponse = Message<"file.ListFilesResponse"> & {
  /**
   * @generated from field: repeated string filenames = 1;
   */
  filenames: string[];
};

/**
 * Describes the message file.ListFilesResponse.
 * Use `create(ListFilesResponseSchema)` to create a new message.
 */
export const ListFilesResponseSchema: GenMessage<ListFilesResponse> = /*@__PURE__*/
  messageDesc(file_file, 1);

/**
 * @generated from service file.FileService
 */
export const FileService: GenService<{
  /**
   * @generated from rpc file.FileService.ListFiles
   */
  listFiles: {
    methodKind: "unary";
    input: typeof ListFilesRequestSchema;
    output: typeof ListFilesResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_file, 0);

