// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file ping.proto (package grpc_backend.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ping.proto.
 */
export const file_ping: GenFile = /*@__PURE__*/
  fileDesc("CgpwaW5nLnByb3RvEg9ncnBjX2JhY2tlbmQudjEiDQoLUGluZ1JlcXVlc3QiHwoMUGluZ1Jlc3BvbnNlEg8KB21lc3NhZ2UYASABKAkyUgoLUGluZ1NlcnZpY2USQwoEUGluZxIcLmdycGNfYmFja2VuZC52MS5QaW5nUmVxdWVzdBodLmdycGNfYmFja2VuZC52MS5QaW5nUmVzcG9uc2VCI1ohZ3JwY19iYWNrZW5kL3NyYy9fZ2VuZXJhdGVkL3Byb3RvYgZwcm90bzM");

/**
 * @generated from message grpc_backend.v1.PingRequest
 */
export type PingRequest = Message<"grpc_backend.v1.PingRequest"> & {
};

/**
 * Describes the message grpc_backend.v1.PingRequest.
 * Use `create(PingRequestSchema)` to create a new message.
 */
export const PingRequestSchema: GenMessage<PingRequest> = /*@__PURE__*/
  messageDesc(file_ping, 0);

/**
 * @generated from message grpc_backend.v1.PingResponse
 */
export type PingResponse = Message<"grpc_backend.v1.PingResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message grpc_backend.v1.PingResponse.
 * Use `create(PingResponseSchema)` to create a new message.
 */
export const PingResponseSchema: GenMessage<PingResponse> = /*@__PURE__*/
  messageDesc(file_ping, 1);

/**
 * @generated from service grpc_backend.v1.PingService
 */
export const PingService: GenService<{
  /**
   * @generated from rpc grpc_backend.v1.PingService.Ping
   */
  ping: {
    methodKind: "unary";
    input: typeof PingRequestSchema;
    output: typeof PingResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_ping, 0);

