// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file proto/v1/order.proto (package api.v1.order, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/v1/order.proto.
 */
export const file_proto_v1_order: GenFile = /*@__PURE__*/
  fileDesc("ChRwcm90by92MS9vcmRlci5wcm90bxIMYXBpLnYxLm9yZGVyInYKBU9yZGVyEg8KB3VzZXJfaWQYASABKAMSEAoIb3JkZXJfaWQYAiABKAMSEAoIdXNlcm5hbWUYAyABKAkSEgoKcHJvZHVjdF9pZBgEIAEoAxIQCghxdWFudGl0eRgFIAEoAxISCgpvcmRlcl9kYXRlGAYgASgJIiQKEUxpc3RPcmRlcnNSZXF1ZXN0Eg8KB3VzZXJfaWQYASABKAMiOAoSTGlzdE9yZGVyc1Jlc3BvbnNlEiIKBU9yZGVyGAEgASgLMhMuYXBpLnYxLm9yZGVyLk9yZGVyIksKEkNyZWF0ZU9yZGVyUmVxdWVzdBIPCgd1c2VyX2lkGAEgASgDEhIKCnByb2R1Y3RfaWQYAiABKAMSEAoIcXVhbnRpdHkYAyABKAMiOQoTQ3JlYXRlT3JkZXJSZXNwb25zZRIiCgVPcmRlchgBIAEoCzITLmFwaS52MS5vcmRlci5PcmRlcjKfAgoNT3JkZXJzU2VydmljZRKEAQoKTGlzdE9yZGVycxIfLmFwaS52MS5vcmRlci5MaXN0T3JkZXJzUmVxdWVzdBogLmFwaS52MS5vcmRlci5MaXN0T3JkZXJzUmVzcG9uc2UiMYLT5JMCKzoBKiImL2FwaS52MS5vcmRlci5PcmRlcnNTZXJ2aWNlL0xpc3RPcmRlcnMwARKGAQoLQ3JlYXRlT3JkZXISIC5hcGkudjEub3JkZXIuQ3JlYXRlT3JkZXJSZXF1ZXN0GiEuYXBpLnYxLm9yZGVyLkNyZWF0ZU9yZGVyUmVzcG9uc2UiMoLT5JMCLDoBKiInL2FwaS52MS5vcmRlci5PcmRlcnNTZXJ2aWNlL0NyZWF0ZU9yZGVyQi9aLWdycGNfYmFja2VuZC9zcmMvX2dlbmVyYXRlZC9wcm90by92MTtwcm90b192MWIGcHJvdG8z", [file_google_api_annotations]);

/**
 * @generated from message api.v1.order.Order
 */
export type Order = Message<"api.v1.order.Order"> & {
  /**
   * @generated from field: int64 user_id = 1;
   */
  userId: bigint;

  /**
   * @generated from field: int64 order_id = 2;
   */
  orderId: bigint;

  /**
   * @generated from field: string username = 3;
   */
  username: string;

  /**
   * @generated from field: int64 product_id = 4;
   */
  productId: bigint;

  /**
   * @generated from field: int64 quantity = 5;
   */
  quantity: bigint;

  /**
   * @generated from field: string order_date = 6;
   */
  orderDate: string;
};

/**
 * Describes the message api.v1.order.Order.
 * Use `create(OrderSchema)` to create a new message.
 */
export const OrderSchema: GenMessage<Order> = /*@__PURE__*/
  messageDesc(file_proto_v1_order, 0);

/**
 * @generated from message api.v1.order.ListOrdersRequest
 */
export type ListOrdersRequest = Message<"api.v1.order.ListOrdersRequest"> & {
  /**
   * @generated from field: int64 user_id = 1;
   */
  userId: bigint;
};

/**
 * Describes the message api.v1.order.ListOrdersRequest.
 * Use `create(ListOrdersRequestSchema)` to create a new message.
 */
export const ListOrdersRequestSchema: GenMessage<ListOrdersRequest> = /*@__PURE__*/
  messageDesc(file_proto_v1_order, 1);

/**
 * @generated from message api.v1.order.ListOrdersResponse
 */
export type ListOrdersResponse = Message<"api.v1.order.ListOrdersResponse"> & {
  /**
   * @generated from field: api.v1.order.Order Order = 1;
   */
  Order?: Order;
};

/**
 * Describes the message api.v1.order.ListOrdersResponse.
 * Use `create(ListOrdersResponseSchema)` to create a new message.
 */
export const ListOrdersResponseSchema: GenMessage<ListOrdersResponse> = /*@__PURE__*/
  messageDesc(file_proto_v1_order, 2);

/**
 * @generated from message api.v1.order.CreateOrderRequest
 */
export type CreateOrderRequest = Message<"api.v1.order.CreateOrderRequest"> & {
  /**
   * @generated from field: int64 user_id = 1;
   */
  userId: bigint;

  /**
   * @generated from field: int64 product_id = 2;
   */
  productId: bigint;

  /**
   * @generated from field: int64 quantity = 3;
   */
  quantity: bigint;
};

/**
 * Describes the message api.v1.order.CreateOrderRequest.
 * Use `create(CreateOrderRequestSchema)` to create a new message.
 */
export const CreateOrderRequestSchema: GenMessage<CreateOrderRequest> = /*@__PURE__*/
  messageDesc(file_proto_v1_order, 3);

/**
 * @generated from message api.v1.order.CreateOrderResponse
 */
export type CreateOrderResponse = Message<"api.v1.order.CreateOrderResponse"> & {
  /**
   * @generated from field: api.v1.order.Order Order = 1;
   */
  Order?: Order;
};

/**
 * Describes the message api.v1.order.CreateOrderResponse.
 * Use `create(CreateOrderResponseSchema)` to create a new message.
 */
export const CreateOrderResponseSchema: GenMessage<CreateOrderResponse> = /*@__PURE__*/
  messageDesc(file_proto_v1_order, 4);

/**
 * @generated from service api.v1.order.OrdersService
 */
export const OrdersService: GenService<{
  /**
   * @generated from rpc api.v1.order.OrdersService.ListOrders
   */
  listOrders: {
    methodKind: "server_streaming";
    input: typeof ListOrdersRequestSchema;
    output: typeof ListOrdersResponseSchema;
  },
  /**
   * @generated from rpc api.v1.order.OrdersService.CreateOrder
   */
  createOrder: {
    methodKind: "unary";
    input: typeof CreateOrderRequestSchema;
    output: typeof CreateOrderResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proto_v1_order, 0);

