// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file proto/v1/user.proto (package api.v1.user, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_api_annotations } from "../../google/api/annotations_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file proto/v1/user.proto.
 */
export const file_proto_v1_user: GenFile = /*@__PURE__*/
  fileDesc("ChNwcm90by92MS91c2VyLnByb3RvEgthcGkudjEudXNlciI4CgRVc2VyEg8KB3VzZXJfaWQYASABKAMSEAoIdXNlcm5hbWUYAiABKAkSDQoFZW1haWwYAyABKAkiEQoPTGlzdFVzZXJSZXF1ZXN0IjQKEExpc3RVc2VyUmVzcG9uc2USIAoFdXNlcnMYASADKAsyES5hcGkudjEudXNlci5Vc2VyMoYBCgtVc2VyU2VydmljZRJ3CglMaXN0VXNlcnMSHC5hcGkudjEudXNlci5MaXN0VXNlclJlcXVlc3QaHS5hcGkudjEudXNlci5MaXN0VXNlclJlc3BvbnNlIi2C0+STAic6ASoiIi9hcGkudjEudXNlci5Vc2VyU2VydmljZS9MaXN0VXNlcnNCL1otZ3JwY19iYWNrZW5kL3NyYy9fZ2VuZXJhdGVkL3Byb3RvL3YxO3Byb3RvX3YxYgZwcm90bzM", [file_google_api_annotations]);

/**
 * @generated from message api.v1.user.User
 */
export type User = Message<"api.v1.user.User"> & {
  /**
   * @generated from field: int64 user_id = 1;
   */
  userId: bigint;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;
};

/**
 * Describes the message api.v1.user.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_proto_v1_user, 0);

/**
 * @generated from message api.v1.user.ListUserRequest
 */
export type ListUserRequest = Message<"api.v1.user.ListUserRequest"> & {
};

/**
 * Describes the message api.v1.user.ListUserRequest.
 * Use `create(ListUserRequestSchema)` to create a new message.
 */
export const ListUserRequestSchema: GenMessage<ListUserRequest> = /*@__PURE__*/
  messageDesc(file_proto_v1_user, 1);

/**
 * @generated from message api.v1.user.ListUserResponse
 */
export type ListUserResponse = Message<"api.v1.user.ListUserResponse"> & {
  /**
   * @generated from field: repeated api.v1.user.User users = 1;
   */
  users: User[];
};

/**
 * Describes the message api.v1.user.ListUserResponse.
 * Use `create(ListUserResponseSchema)` to create a new message.
 */
export const ListUserResponseSchema: GenMessage<ListUserResponse> = /*@__PURE__*/
  messageDesc(file_proto_v1_user, 2);

/**
 * @generated from service api.v1.user.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc api.v1.user.UserService.ListUsers
   */
  listUsers: {
    methodKind: "unary";
    input: typeof ListUserRequestSchema;
    output: typeof ListUserResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_proto_v1_user, 0);

