// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

type Order struct {
	OrderID   int64
	UserID    int64
	ProductID int64
	OrderDate string
	Quantity  int64
}

type Payment struct {
	PaymentID   int64
	OrderID     int64
	PaymentDate string
	Amount      float64
}

type Product struct {
	ProductID     int64
	ProductName   string
	Price         float64
	StockQuantity int64
}

type User struct {
	UserID   int64
	Username string
	Email    string
}
